"""
AI Image Metadata Checker
Scans image files for metadata indicators of AI generation
Includes spectral/frequency analysis for detecting AI patterns
"""

import os
import json
from pathlib import Path
from typing import Dict, List, Tuple, Optional
from PIL import Image
from PIL.ExifTags import TAGS, GPSTAGS
import numpy as np
from scipy import fftpack
from scipy.stats import entropy


AI_INDICATORS = {
    "c2pa": ["c2pa", "contentauth", "manifest"],
    "openai": ["openai", "dall-e", "dalle", "chatgpt", "dall·e"],
    "midjourney": ["midjourney", "mj", "mid-journey"],
    "stablediffusion": ["stable diffusion", "sdxl", "sd", "stabilityai", "stable-diffusion"],
    "adobe": ["adobe firefly", "firefly", "photoshop ai", "generative ai"],
    "google": ["gemini", "imagen", "google ai", "bard"],
    "nvidia": ["nvidia canvas", "canvas", "nvidia ai"],
    "dall_e": ["dall-e", "dall3"],
    "flux": ["flux", "black forest labs"],
    "generic_ai": ["ai generated", "ai-generated", "synthetic", "generated by", "created by ai"],
    "created_software": ["created software", "software agent", "generator", "creation software"],
}


AI_FILENAME_PATTERNS = [
    "midjourney", "mj-", "sd-", "sdxl", "flux-", 
    "dalle", "ai-", "generated", "synthetic",
    "stable_diffusion", "comfyui", "invokeai",
    "gemini_", "imagen_", "firefly_",
    "_by_ai", "_ai_", "ai_art", "ai_image"
]


class AIMetadataChecker:
    def __init__(self):
        self.findings = []
        self.confidence = 0.0
    
    def check_file(self, file_path: str) -> Dict:
        """Check an image file for AI metadata indicators"""
        self.findings = []
        self.confidence = 0.0
        
        if not os.path.exists(file_path):
            return {"error": "File not found", "is_ai": None, "confidence": 0}
        
        try:
            with Image.open(file_path) as img:
                self._check_exif(img)
                self._check_xmp(img)
                self._check_filename(file_path)
                self._check_png_chunks(img, file_path)
                self._check_dimensions_and_aspect(img)
                self._check_spectral_analysis(img)
        except Exception as e:
            return {"error": str(e), "is_ai": None, "confidence": 0}
        
        is_ai = self.confidence > 50
        
        return {
            "is_ai": is_ai,
            "confidence": self.confidence,
            "findings": self.findings,
            "file": os.path.basename(file_path)
        }
    
    def check_bytes(self, image_bytes: bytes) -> Dict:
        """Check image from bytes"""
        self.findings = []
        self.confidence = 0.0
        
        try:
            from io import BytesIO
            with Image.open(BytesIO(image_bytes)) as img:
                self._check_exif(img)
                self._check_xmp(img)
                self._check_png_chunks_bytes(BytesIO(image_bytes))
                self._check_dimensions_and_aspect(img)
                self._check_spectral_analysis(img)
        except Exception as e:
            return {"error": str(e), "is_ai": None, "confidence": 0}
        
        is_ai = self.confidence > 50
        
        return {
            "is_ai": is_ai,
            "confidence": self.confidence,
            "findings": self.findings,
            "file": "uploaded_image"
        }
    
    def _add_finding(self, indicator: str, confidence: int, details: str = ""):
        """Add a finding with confidence score"""
        self.findings.append({
            "indicator": indicator,
            "confidence": confidence,
            "details": details
        })
        self.confidence = max(self.confidence, confidence)
    
    def _check_exif(self, img: Image.Image):
        """Check EXIF data for AI indicators"""
        exif_data = img.getexif()
        if not exif_data:
            return
        
        exif_string = ""
        for tag_id, value in exif_data.items():
            tag = TAGS.get(tag_id, tag_id)
            if isinstance(value, bytes):
                try:
                    value = value.decode()
                except:
                    continue
            exif_string += f"{tag}: {value} "
        
        exif_lower = exif_string.lower()
        
        for ai_type, keywords in AI_INDICATORS.items():
            for kw in keywords:
                if kw.lower() in exif_lower:
                    self._add_finding(f"EXIF: {ai_type}", 80, f"Found '{kw}' in EXIF data")
    
    def _check_xmp(self, img: Image.Image):
        """Check XMP data for AI indicators"""
        try:
            xmp = img.getxmp()
            if xmp:
                xmp_str = json.dumps(xmp).lower()
                
                for ai_type, keywords in AI_INDICATORS.items():
                    for kw in keywords:
                        if kw.lower() in xmp_str:
                            self._add_finding(f"XMP: {ai_type}", 85, f"Found '{kw}' in XMP data")
        except:
            pass
    
    def _check_filename(self, file_path: str):
        """Check filename for AI indicators"""
        filename = os.path.basename(file_path).lower()
        
        for pattern in AI_FILENAME_PATTERNS:
            if pattern in filename:
                self._add_finding("Filename", 40, f"AI pattern '{pattern}' in filename")
    
    def _check_png_chunks(self, img: Image.Image, file_path: str):
        """Check PNG chunks for AI indicators (C2PA, etc.)"""
        if img.format != 'PNG':
            return
        
        try:
            with open(file_path, 'rb') as f:
                f.read(8)
                while True:
                    length = f.read(4)
                    if len(length) < 4:
                        break
                    chunk_type = f.read(4).decode('latin-1')
                    if chunk_type == 'tEXt' or chunk_type == 'iTXt':
                        data = f.read(int.from_bytes(length, 'big'))
                        data_str = data.decode('latin-1', errors='ignore').lower()
                        
                        for ai_type, keywords in AI_INDICATORS.items():
                            for kw in keywords:
                                if kw.lower() in data_str:
                                    self._add_finding(f"PNG: {ai_type}", 75, f"Found '{kw}' in PNG chunk")
                    
                    if chunk_type == 'IEND':
                        break
                    
                    f.read(int.from_bytes(length, 'big'))
                    f.read(4)
        except:
            pass
    
    def _check_png_chunks_bytes(self, file_obj):
        """Check PNG chunks from bytes"""
        try:
            file_obj.seek(0)
            file_obj.read(8)
            while True:
                length = file_obj.read(4)
                if len(length) < 4:
                    break
                chunk_type = file_obj.read(4).decode('latin-1')
                if chunk_type == 'tEXt' or chunk_type == 'iTXt':
                    data = file_obj.read(int.from_bytes(length, 'big'))
                    data_str = data.decode('latin-1', errors='ignore').lower()
                    
                    for ai_type, keywords in AI_INDICATORS.items():
                        for kw in keywords:
                            if kw.lower() in data_str:
                                self._add_finding(f"PNG: {ai_type}", 75, f"Found '{kw}' in PNG chunk")
                
                if chunk_type == 'IEND':
                    break
                
                file_obj.read(int.from_bytes(length, 'big'))
                file_obj.read(4)
        except:
            pass
    
    def _check_dimensions_and_aspect(self, img: Image.Image):
        """Check for AI-like dimensions (square, power of 2, etc.)"""
        width, height = img.size
        
        if width == height and width in [512, 768, 1024, 1024, 1536, 2048]:
            self._add_finding("Dimensions", 15, f"Square {width}x{height} (common AI size)")
        
        if width % 64 == 0 and height % 64 == 0:
            self._add_finding("Dimensions", 10, "Dimensions are multiples of 64 (common in AI)")
    
    def _check_spectral_analysis(self, img: Image.Image):
        """
        Spectral/frequency analysis to detect AI-generated images.
        AI-generated images tend to have different frequency patterns than real photos.
        """
        try:
            img_arr = np.array(img.convert('L'))
            
            if img_arr.shape[0] < 64 or img_arr.shape[1] < 64:
                return
            
            fft2 = fftpack.fft2(img_arr)
            fft_shift = fftpack.fftshift(fft2)
            magnitude = np.abs(fft_shift)
            
            log_magnitude = np.log1p(magnitude)
            
            h, w = log_magnitude.shape
            center_h, center_w = h // 2, w // 2
            
            low_freq_region = log_magnitude[center_h-10:center_h+10, center_w-10:center_w+10]
            high_freq_region = np.concatenate([
                log_magnitude[:20, :].flatten(),
                log_magnitude[-20:, :].flatten(),
                log_magnitude[:, :20].flatten(),
                log_magnitude[:, -20:].flatten()
            ])
            
            low_mean = np.mean(low_freq_region)
            high_mean = np.mean(high_freq_region)
            high_to_low_ratio = high_mean / (low_mean + 1e-10)
            
            freq_variance = np.var(log_magnitude)
            freq_entropy = entropy(np.histogram(log_magnitude, bins=50)[0] + 1e-10)
            
            if high_to_low_ratio > 0.35:
                self._add_finding("Spectral-HF", 35, f"High frequency ratio: {high_to_low_ratio:.3f} (AI indicator)")
            
            if freq_entropy < 4.5:
                self._add_finding("Spectral-ENT", 30, f"Low frequency entropy: {freq_entropy:.2f} (unusual pattern)")
            
            if freq_variance > 1.5:
                self._add_finding("Spectral-VAR", 25, f"High frequency variance: {freq_variance:.2f}")
            
            center_region = log_magnitude[center_h-5:center_h+5, center_w-5:center_w+5]
            if np.std(center_region) < 0.1:
                self._add_finding("Spectral-CENTER", 20, "Very smooth center frequency (common in AI)")
                
        except Exception as e:
            pass


def check_image_ai_metadata(image_path: str) -> Dict:
    """Convenience function to check if an image has AI metadata"""
    checker = AIMetadataChecker()
    return checker.check_file(image_path)


def check_image_ai_metadata_bytes(image_bytes: bytes) -> Dict:
    """Convenience function to check image from bytes"""
    checker = AIMetadataChecker()
    return checker.check_bytes(image_bytes)


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        result = check_image_ai_metadata(sys.argv[1])
        print(json.dumps(result, indent=2))
    else:
        print("Usage: python ai_metadata_checker.py <image_path>")
